spring:
  application:
    name: craft-search
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.36.43.57:3306/craft?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  mvc:
    view:
      prefix: /static/jsp/
      suffix: .jsp


mybatis:
  type-aliases-package: com/zkwp/search
  mapper-locations: classpath:mapper/*.xml


server:
  port: 8004
  servlet:
    context-path: /craft/search


eureka:
  client:  #客户端注册进eureka
    service-url:
      defaultZone: http://eureka.zkwp.com:7001/eureka/
  instance:
    instance-id: search
    prefer-ip-address: true
